/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

    package Aplikasi;
    import javax.swing.*;
    import java.sql.*;
    import javax.swing.table.*;
    import java.util.Date;
    import java.text.SimpleDateFormat;
    import java.awt.Dimension;
    import java.awt.Toolkit;
/**
 *
 * @author Dewa Pradipta Putra
 */
public class FormKendaraanKeluar extends javax.swing.JFrame {
    String notiket;
String tanggalmasuk;
String noplat;
String jeniskendaraan;
String jammasuk;
DefaultTableModel tabMode;
Connection koneksi;

public FormKendaraanKeluar() {
        initComponents();
        Object[] row= {"No.Tiket","Tgl Masuk", "No.Plat", "J.Kendaraan", "Jam Masuk"};
        tabMode=new DefaultTableModel(null,row);
        tabeldata.setModel(tabMode);

        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    
    }


    public void konekdatabase(){
try{

koneksi =DriverManager.getConnection("jdbc:mysql://localhost:3306/datalogin","root","");
}
catch (Exception e)
{
System.err.println("Exception: "+e.getMessage());
}
}
    public void hapustabel(){
int row=tabMode.getRowCount();
for(int i=0;i<row;i++){
tabMode.removeRow(0);
}
}
    public void tampildataketabel(){
hapustabel();
try{
String sql="Select * from parkirmasuk";
Statement stat=koneksi.createStatement();
ResultSet set=stat.executeQuery(sql);
while (set.next()){
notiket=set.getString("notiket");
tanggalmasuk=set.getString("tanggalmasuk");
noplat=set.getString("noplat");
jeniskendaraan=set.getString("jeniskendaraan");
jammasuk=set.getString("jammasuk");

String[] data={notiket,tanggalmasuk,noplat,jeniskendaraan,jammasuk};
tabMode.addRow(data);
}
}
catch(Exception e){
}
}
public void clear(){
noTiket.setText("");
platNomor.setText("");
jamMasuk.setText("");

}
    public void simpandata(){
notiket=noTiket.getText();
tanggalmasuk=tftanggal.getText();
noplat=platNomor.getText();
jeniskendaraan=(String)jenis.getSelectedItem();
jammasuk=jamMasuk.getText();

try{
konekdatabase();
Statement statement=koneksi.createStatement();
String sql="insert into parkirmasuk values ('"+notiket+"','"+tanggalmasuk+"','"+noplat+
"','"+jeniskendaraan+"','"+jammasuk+"');";
statement.executeUpdate(sql);
statement.close();
clear();
}
catch (SQLException e){
    System.out.println(e.getMessage());
}
}
    public void data(){
notiket=noTiket.getText();
tanggalmasuk=tftanggal.getText();
noplat=platNomor.getText();
jeniskendaraan=(String)jenis.getSelectedItem();
jammasuk=jamMasuk.getText();

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noTiket = new javax.swing.JTextField();
        platNomor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        tftanggal = new javax.swing.JTextField();
        jamMasuk = new javax.swing.JTextField();
        btmenu = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        btcari = new javax.swing.JButton();
        btkeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Kendaraan Keluar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("No.Tiket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Plat nomor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Kendaraan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        noTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTiketActionPerformed(evt);
            }
        });
        getContentPane().add(noTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 124, 32));

        platNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platNomorActionPerformed(evt);
            }
        });
        getContentPane().add(platNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 124, 32));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 920, 11));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 126, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Pictures\\PBO images\\op.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Masuk");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Jam Masuk");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 124, 30));

        tftanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tftanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 120, 32));

        jamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamMasukActionPerformed(evt);
            }
        });
        getContentPane().add(jamMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, 32));

        btmenu.setText("Menu");
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 90, 30));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 90, 30));

        btcari.setText("Cari");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 90, 30));

        btkeluar.setText("Keluar");
        btkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 90, 30));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.Tiket", "Tgl.Masuk", "No.Plat", "J.Kendaraaan", "Jam Masuk"
            }
        ));
        jScrollPane3.setViewportView(tabeldata);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 570, 130));

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 190));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 610, 160));

        setBounds(0, 0, 626, 525);
    }// </editor-fold>//GEN-END:initComponents

    private void noTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTiketActionPerformed

    private void platNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platNomorActionPerformed

    private void tftanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalActionPerformed

    private void jamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamMasukActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
    selamatDatang a = new selamatDatang();
     a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btmenuActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
    konekdatabase();
        try
        {
            String cari=noTiket.getText();
            Statement statement=koneksi.createStatement();
            String sql="select * from parkirmasuk where notiket like '"+cari+"'";
            ResultSet rs=statement.executeQuery(sql);
            if(rs.next())
            {
                noTiket.setText(rs.getString(1));
                tftanggal.setText(rs.getString(2));
                platNomor.setText(rs.getString(3));
                jenis.setSelectedItem(rs.getString(4));
                jamMasuk.setText(rs.getString(5));
                }
            else{
                JOptionPane.showMessageDialog(null, "KENDARAAN SUDAH KELUAR");
            }
            statement.close();
            koneksi.close();
        }
        catch (Exception ex)
        {
            System.out.println("Error: "+ex);
        }     
// TODO add your handling code here:
    }//GEN-LAST:event_btcariActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
    if(noTiket.equals("")||tftanggal.equals("")||platNomor.equals("")||jenis.equals("")||jamMasuk.equals(""))
        {
            JOptionPane.showMessageDialog(null, "HARAP MASUKAN DATA LENGKAP!");
        }
        else{
            simpandata();
            tampildataketabel();
        }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkeluarActionPerformed
           String notiket = noTiket.getText();
        try {
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/datalogin", "root", "");
            Statement statement = (Statement) koneksi.createStatement();
            statement.executeUpdate("delete from parkirmasuk where notiket= ('"+notiket+"');");
            clear();
            hapustabel();
            tampildataketabel();
            JOptionPane.showMessageDialog(null, "Kendaraan Keluar!");
        }catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal");
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_btkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKendaraanKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKendaraanKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKendaraanKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKendaraanKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKendaraanKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcari;
    private javax.swing.JButton btkeluar;
    private javax.swing.JButton btmenu;
    private javax.swing.JButton btsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jamMasuk;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField noTiket;
    private javax.swing.JTextField platNomor;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tftanggal;
    // End of variables declaration//GEN-END:variables
}
