/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Dimension;
import java.awt.Toolkit;
import com.mysql.jdbc.Driver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Dewa Pradipta Putra
 */
public class FormKendaraaanMasuk extends javax.swing.JFrame {

String notiket;
String tanggalmasuk;
String noplat;
String jeniskendaraan;
String jammasuk;
DefaultTableModel tabMode;
Connection koneksi;

public FormKendaraaanMasuk() {
        initComponents();
        Object[] row= {"No.Tiket","Tgl Masuk", "No.Plat", "J.Kendaraan", "Jam Masuk"};
        tabMode=new DefaultTableModel(null,row);
        tabeldata.setModel(tabMode);
        tglskrg();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    
    }
public void tglskrg(){
Date skrg= new Date();
SimpleDateFormat format= new SimpleDateFormat("dd-MM-yyyy");
String tgl = format.format(skrg);
tftanggal.setText(format.format(skrg));
}
    public void konekdatabase(){
try{

koneksi =DriverManager.getConnection("jdbc:mysql://localhost:3306/datalogin","root","");
}
catch (Exception e)
{
System.err.println("Exception: "+e.getMessage());
}
}
    public void hapustabel(){
int row=tabMode.getRowCount();
for(int i=0;i<row;i++){
tabMode.removeRow(0);
}
}public void tampildataketabel(){
hapustabel();
try{
String sql="Select * from parkirmasuk";
Statement stat=koneksi.createStatement();
ResultSet set=stat.executeQuery(sql);
while (set.next()){
notiket=set.getString("notiket");
tanggalmasuk=set.getString("tanggalmasuk");
noplat=set.getString("noplat");
jeniskendaraan=set.getString("jeniskendaraan");
jammasuk=set.getString("jammasuk");
String[] data={notiket,tanggalmasuk,noplat,jeniskendaraan,jammasuk};
tabMode.addRow(data);
} }
catch(Exception e){
} }
public void clear(){
noTiket.setText("");
platNomor.setText("");
jamMasuk.setText("");
}
    public void simpandata(){
notiket=noTiket.getText();
tanggalmasuk=tftanggal.getText();
noplat=platNomor.getText();
jeniskendaraan=(String)jenis.getSelectedItem();
jammasuk=jamMasuk.getText();
try{
konekdatabase();
Statement statement=koneksi.createStatement();
String sql="insert into parkirmasuk values ('"+notiket+"','"+tanggalmasuk+"','"+noplat+
"','"+jeniskendaraan+"','"+jammasuk+"','','');";
statement.executeUpdate(sql);
statement.close();
clear();
}
catch (SQLException e){
    System.out.println(e.getMessage());
}
}
    public void data(){
notiket=noTiket.getText();
tanggalmasuk=tftanggal.getText();
noplat=platNomor.getText();
jeniskendaraan=(String)jenis.getSelectedItem();
jammasuk=jamMasuk.getText();
}
    

    /**
     * Creates new form FormKendaraaanMasuk
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noTiket = new javax.swing.JTextField();
        platNomor = new javax.swing.JTextField();
        jamMasuk = new javax.swing.JTextField();
        tftanggal = new javax.swing.JTextField();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btcari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("No.Tiket");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 61, 47, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Plat Nomor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 94, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Kendaraan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 134, 87, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal Masuk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 166, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jam Masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 204, 58, 15);

        noTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTiketActionPerformed(evt);
            }
        });
        getContentPane().add(noTiket);
        noTiket.setBounds(130, 54, 116, 30);

        platNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platNomorActionPerformed(evt);
            }
        });
        getContentPane().add(platNomor);
        platNomor.setBounds(130, 94, 116, 30);

        jamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamMasukActionPerformed(evt);
            }
        });
        getContentPane().add(jamMasuk);
        jamMasuk.setBounds(131, 202, 116, 30);

        tftanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tftanggal);
        tftanggal.setBounds(131, 164, 116, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        getContentPane().add(jenis);
        jenis.setBounds(130, 134, 116, 20);

        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 0, 0);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 0, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Pictures\\PBO images\\Untitled-1.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 94, 100, 100);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 250, 452, 9);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 47, 452, 6);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 11, 59, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Kendaraan  Masuk");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(149, 11, 230, 29);

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.Tiket", "Tgl. Masuk", "No. Plat", "J.Kendaraan", "Jam Masuk"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 452, 141);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jPanel3.setBackground(new java.awt.Color(252, 91, 91));

        btcari.setText("Cari");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btcari, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(btcari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(260, 0, 210, 440);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btsimpan.setText("Simpan");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(btsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 260, 440);

        setBounds(0, 0, 488, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void noTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTiketActionPerformed

    private void jamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamMasukActionPerformed

    private void tftanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        if(noTiket.equals("")||tftanggal.equals("")||platNomor.equals("")||jenis.equals("")||jamMasuk.equals(""))
        {
            JOptionPane.showMessageDialog(null, "HARAP MASUKAN DATA LENGKAP!");
        }
        else{
            simpandata();
            tampildataketabel();
        }
    
// TODO add your handling code here:
    }//GEN-LAST:event_btsimpanActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
    konekdatabase();
        try
        {
            String cari=noTiket.getText();
            Statement statement=koneksi.createStatement();
            String sql="select * from parkirmasuk where notiket like '"+cari+"'";
            ResultSet rs=statement.executeQuery(sql);
            if(rs.next())
            {
                noTiket.setText(rs.getString(1));
                tftanggal.setText(rs.getString(2));
                platNomor.setText(rs.getString(3));
                jenis.setSelectedItem(rs.getString(4));
                jamMasuk.setText(rs.getString(5));
                }
            else{
                JOptionPane.showMessageDialog(null, "DATA TIDAK ADA DALAM DATABASE");
            }
            statement.close();
            koneksi.close();
        }
        catch (Exception ex)
        {
            System.out.println("Error: "+ex);
        }     
        
// TODO add your handling code here:
    }//GEN-LAST:event_btcariActionPerformed

    private void platNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platNomorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    selamatDatang a = new selamatDatang();
     a.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKendaraaanMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKendaraaanMasuk().setVisible(true);
            }
        });
    }
    public Statement stat;
    public ResultSet set;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcari;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jamMasuk;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField noTiket;
    private javax.swing.JTextField platNomor;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tftanggal;
    // End of variables declaration//GEN-END:variables
}


